custom_filtering=true
# custom_filtering=false
if [ "$custom_filtering" = true ] ; then
    type=custom
else
    type=default
fi

# preprocessing=none
# preprocessing=single
preprocessing=mutual

confidence=0.1
# confidence=0.5
# confidence=0.01

coarse_level=-2
# coarse_level=-3

index_coarse_feats=1
# index_coarse_feats=2

rm -rf TestData/FullNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}
mkdir TestData/FullNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}
rm -rf TestData/FullDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}
mkdir TestData/FullDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}
rm -rf TestData/PartialNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}
mkdir TestData/PartialNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}
rm -rf TestData/PartialDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}
mkdir TestData/PartialDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}

file_name=TestData/type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}.txt
rm ${file_name}
touch ${file_name}

if [ "$custom_filtering" = true ] ; then
    echo 'Full Non Deformed' >> ${file_name} 
    python3 eval_supervised_astrivis.py --config=config/LNDP.yaml --s='FullNonDeformed/mesh_transformed_0.ply' --t='FullNonDeformed/mesh_transformed_1.ply' --source_trans='FullNonDeformed/mesh_transformed_0_se4.h5' --target_trans='FullNonDeformed/mesh_transformed_1_se4.h5' --matches='FullNonDeformed/0_1.npz' --output="FullNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result.ply" --output_trans="FullNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result_se4.h5" --intermediate_output_folder="FullNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/" --base='/home/aiday.kyzy/code/DeformationPyramid/TestData/' --confidence_threshold=${confidence} --preprocessing=${preprocessing} --index_coarse_feats=1 --coarse_level=${coarse_level} --print_keypoints --custom_filtering >> ${file_name}
    python3 ../../code/sfm/python/graphics/mesh/compute_relative_transformation_error.py --part1="TestData/FullNonDeformed/mesh_transformed_0_se4.h5" --part2="TestData/FullNonDeformed/mesh_transformed_1_se4.h5" --pred="TestData/FullNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result_se4.h5" >> ${file_name}
    python3 ../../code/sfm/python/graphics/mesh/compute_pointcloud_rmse_ir.py --input1="TestData/FullNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result.ply" --input2='TestData/FullNonDeformed/mesh_transformed_1.ply' --save_final_path="TestData/FullNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/final.ply" --save_destination_path="TestData/FullNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/destination.ply" >> ${file_name}

    echo 'Partial Deformed' >> ${file_name} 
    python3 eval_supervised_astrivis.py --config=config/LNDP.yaml --s='PartialDeformed/020_0.ply' --t='PartialDeformed/104_1.ply' --source_trans='PartialDeformed/020_0_se4.h5' --target_trans='PartialDeformed/104_1_se4.h5' --matches='PartialDeformed/020_104_0_1.npz' --output="PartialDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result.ply" --output_trans="PartialDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result_se4.h5" --intermediate_output_folder="PartialDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/" --base='/home/aiday.kyzy/code/DeformationPyramid/TestData/' --confidence_threshold=${confidence} --preprocessing=${preprocessing} --index_coarse_feats=1 --coarse_level=${coarse_level} --print_keypoints --custom_filtering >> ${file_name}
    python3 ../../code/sfm/python/graphics/mesh/compute_relative_transformation_error.py --part1="TestData/PartialDeformed/020_0_se4.h5" --part2="TestData/PartialDeformed/104_1_se4.h5" --pred="TestData/PartialDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result_se4.h5" >> ${file_name}
    python3 ../../code/sfm/python/graphics/mesh/compute_pointcloud_rmse_ir.py --final="TestData/PartialDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result.ply" --initial_1='TestData/PartialDeformed/020_0.ply' --initial_2='TestData/PartialDeformed/104_1.ply' --matches='TestData/PartialDeformed/020_104_0_1.npz' --part1="TestData/PartialDeformed/020_0_se4.h5" --part2="TestData/PartialDeformed/104_1_se4.h5" --save_final_path="TestData/PartialDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/final.ply" --save_destination_path="TestData/PartialDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/destination.ply" >> ${file_name}

    echo 'Full Deformed' >> ${file_name} 
    python3 eval_supervised_astrivis.py --config=config/LNDP.yaml --s='FullDeformed/020.ply' --t='FullDeformed/104.ply' --source_trans='FullDeformed/020_se4.h5' --target_trans='FullDeformed/104_se4.h5' --matches='FullDeformed/020_104.npz' --output="FullDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result.ply" --output_trans="FullDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result_se4.h5" --intermediate_output_folder="FullDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/" --base='/home/aiday.kyzy/code/DeformationPyramid/TestData/' --confidence_threshold=${confidence} --preprocessing=${preprocessing} --index_coarse_feats=1 --coarse_level=${coarse_level} --print_keypoints --custom_filtering >> ${file_name}
    python3 ../../code/sfm/python/graphics/mesh/compute_relative_transformation_error.py --part1='TestData/FullDeformed/020_se4.h5' --part2='TestData/FullDeformed/104_se4.h5' --pred="TestData/FullDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result_se4.h5" >> ${file_name}
    python3 ../../code/sfm/python/graphics/mesh/compute_pointcloud_rmse_ir.py --input1="TestData/FullDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result.ply" --input2='TestData/FullDeformed/104.ply' --matches='TestData/FullDeformed/020_104.npz' --save_final_path="TestData/FullDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/final.ply" --save_destination_path="TestData/FullDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/destination.ply" >> ${file_name}

    echo 'Partial Non Deformed' >> ${file_name} 
    python3 eval_supervised_astrivis.py --config=config/LNDP.yaml --s='PartialNonDeformed/mesh_transformed_0.ply' --t='PartialNonDeformed/mesh_transformed_1.ply' --source_trans='PartialNonDeformed/mesh_transformed_0_se4.h5' --target_trans='PartialNonDeformed/mesh_transformed_1_se4.h5' --matches='PartialNonDeformed/0_1.npz' --output="PartialNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result.ply" --output_trans="PartialNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result_se4.h5" --intermediate_output_folder="PartialNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/" --base='/home/aiday.kyzy/code/DeformationPyramid/TestData/' --confidence_threshold=${confidence} --preprocessing=${preprocessing} --index_coarse_feats=1 --coarse_level=${coarse_level} --print_keypoints --custom_filtering >> ${file_name}
    python3 ../../code/sfm/python/graphics/mesh/compute_relative_transformation_error.py --part1='TestData/PartialNonDeformed/mesh_transformed_0_se4.h5' --part2='TestData/PartialNonDeformed/mesh_transformed_1_se4.h5' --pred="TestData/PartialNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result_se4.h5" >> ${file_name}
    python3 ../../code/sfm/python/graphics/mesh/compute_pointcloud_rmse_ir.py --final="TestData/PartialNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result.ply" --initial='TestData/PartialNonDeformed/mesh_transformed_0.ply' --part1='TestData/PartialNonDeformed/mesh_transformed_0_se4.h5' --part2='TestData/PartialNonDeformed/mesh_transformed_1_se4.h5' --save_final_path="TestData/PartialNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/final.ply" --save_destination_path="TestData/PartialNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/destination.ply" >> ${file_name}

else
    echo 'Full Non Deformed' >> ${file_name} 
    python3 eval_supervised_astrivis.py --config=config/LNDP.yaml --s='FullNonDeformed/mesh_transformed_0.ply' --t='FullNonDeformed/mesh_transformed_1.ply' --source_trans='FullNonDeformed/mesh_transformed_0_se4.h5' --target_trans='FullNonDeformed/mesh_transformed_1_se4.h5' --matches='FullNonDeformed/0_1.npz' --output="FullNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result.ply" --output_trans="FullNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result_se4.h5" --intermediate_output_folder="FullNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/" --base='/home/aiday.kyzy/code/DeformationPyramid/TestData/' --confidence_threshold=${confidence} --preprocessing=${preprocessing} --index_coarse_feats=1 --coarse_level=${coarse_level} --print_keypoints >> ${file_name}
    python3 ../../code/sfm/python/graphics/mesh/compute_relative_transformation_error.py --part1="TestData/FullNonDeformed/mesh_transformed_0_se4.h5" --part2="TestData/FullNonDeformed/mesh_transformed_1_se4.h5" --pred="TestData/FullNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result_se4.h5" >> ${file_name}
    python3 ../../code/sfm/python/graphics/mesh/compute_pointcloud_rmse_ir.py --input1="TestData/FullNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result.ply" --input2='TestData/FullNonDeformed/mesh_transformed_1.ply' --save_final_path="TestData/FullNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/final.ply" --save_destination_path="TestData/FullNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/destination.ply" >> ${file_name}

    echo 'Partial Deformed' >> ${file_name} 
    python3 eval_supervised_astrivis.py --config=config/LNDP.yaml --s='PartialDeformed/020_0.ply' --t='PartialDeformed/104_1.ply' --source_trans='PartialDeformed/020_0_se4.h5' --target_trans='PartialDeformed/104_1_se4.h5' --matches='PartialDeformed/020_104_0_1.npz' --output="PartialDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result.ply" --output_trans="PartialDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result_se4.h5" --intermediate_output_folder="PartialDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/" --base='/home/aiday.kyzy/code/DeformationPyramid/TestData/' --confidence_threshold=${confidence} --preprocessing=${preprocessing} --index_coarse_feats=1 --coarse_level=${coarse_level} --print_keypoints >> ${file_name}
    python3 ../../code/sfm/python/graphics/mesh/compute_relative_transformation_error.py --part1="TestData/PartialDeformed/020_0_se4.h5" --part2="TestData/PartialDeformed/104_1_se4.h5" --pred="TestData/PartialDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result_se4.h5" >> ${file_name}
    python3 ../../code/sfm/python/graphics/mesh/compute_pointcloud_rmse_ir.py --final="TestData/PartialDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result.ply" --initial_1='TestData/PartialDeformed/020_0.ply' --initial_2='TestData/PartialDeformed/104_1.ply' --matches='TestData/PartialDeformed/020_104_0_1.npz' --part1="TestData/PartialDeformed/020_0_se4.h5" --part2="TestData/PartialDeformed/104_1_se4.h5" --save_final_path="TestData/PartialDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/final.ply" --save_destination_path="TestData/PartialDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/destination.ply" >> ${file_name}

    echo 'Full Deformed' >> ${file_name} 
    python3 eval_supervised_astrivis.py --config=config/LNDP.yaml --s='FullDeformed/020.ply' --t='FullDeformed/104.ply' --source_trans='FullDeformed/020_se4.h5' --target_trans='FullDeformed/104_se4.h5' --matches='FullDeformed/020_104.npz' --output="FullDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result.ply" --output_trans="FullDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result_se4.h5" --intermediate_output_folder="FullDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/" --base='/home/aiday.kyzy/code/DeformationPyramid/TestData/' --confidence_threshold=${confidence} --preprocessing=${preprocessing} --index_coarse_feats=1 --coarse_level=${coarse_level} --print_keypoints >> ${file_name}
    python3 ../../code/sfm/python/graphics/mesh/compute_relative_transformation_error.py --part1='TestData/FullDeformed/020_se4.h5' --part2='TestData/FullDeformed/104_se4.h5' --pred="TestData/FullDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result_se4.h5" >> ${file_name}
    python3 ../../code/sfm/python/graphics/mesh/compute_pointcloud_rmse_ir.py --input1="TestData/FullDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result.ply" --input2='TestData/FullDeformed/104.ply' --matches='TestData/FullDeformed/020_104.npz' --save_final_path="TestData/FullDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/final.ply" --save_destination_path="TestData/FullDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/destination.ply" >> ${file_name}

    echo 'Partial Non Deformed' >> ${file_name} 
    python3 eval_supervised_astrivis.py --config=config/LNDP.yaml --s='PartialNonDeformed/mesh_transformed_0.ply' --t='PartialNonDeformed/mesh_transformed_1.ply' --source_trans='PartialNonDeformed/mesh_transformed_0_se4.h5' --target_trans='PartialNonDeformed/mesh_transformed_1_se4.h5' --matches='PartialNonDeformed/0_1.npz' --output="PartialNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result.ply" --output_trans="PartialNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result_se4.h5" --intermediate_output_folder="PartialNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/" --base='/home/aiday.kyzy/code/DeformationPyramid/TestData/' --confidence_threshold=${confidence} --preprocessing=${preprocessing} --index_coarse_feats=1 --coarse_level=${coarse_level} --print_keypoints >> ${file_name}
    python3 ../../code/sfm/python/graphics/mesh/compute_relative_transformation_error.py --part1='TestData/PartialNonDeformed/mesh_transformed_0_se4.h5' --part2='TestData/PartialNonDeformed/mesh_transformed_1_se4.h5' --pred="TestData/PartialNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result_se4.h5" >> ${file_name}
    python3 ../../code/sfm/python/graphics/mesh/compute_pointcloud_rmse_ir.py --final="TestData/PartialNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/result.ply" --initial='TestData/PartialNonDeformed/mesh_transformed_0.ply' --part1='TestData/PartialNonDeformed/mesh_transformed_0_se4.h5' --part2='TestData/PartialNonDeformed/mesh_transformed_1_se4.h5' --save_final_path="TestData/PartialNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/final.ply" --save_destination_path="TestData/PartialNonDeformed/output_type_${type}_preprocessing_${preprocessing}_confidence_${confidence}_coarse_level_${coarse_level}_index_coarse_${index_coarse_feats}/destination.ply" >> ${file_name}

fi