matcher_config: 'correspondence/configs/lepard_fcgf.yaml'
matcher_weights: 'correspondence/pretrained/lepard_epoch_1_fcgf_test_iter_10.pth'

outlier_rejection_config: 'correspondence/configs/outlier_rejection.yaml'
outlier_rejection_weights: 'correspondence/pretrained/outlier_weights.pth'


mode: test
gpu_mode:  True

exp_dir: None


#dataset:
dataset: 4dmatch
folder: deploy
batch_size: 1
num_workers: 1
augment_noise: 0.002
data_root: /path/to/4DMatch
split: {
  "train": split/train,
  "val": split/4DLoMatch,
  "test": split/4DMatch
}
